pluginManagement {
    repositories {
        gradlePluginPortal()
        // For SNAPSHOTS
        maven { url "https://central.sonatype.com/repository/maven-snapshots/" }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'io.neow3j.gradle-plugin') {
                useModule("io.neow3j:gradle-plugin:${requested.version}")
            }
        }
    }
}
rootProject.name = 'grantshares-contracts'
