name: grantshares-ci-cd

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '8'
          cache: 'gradle'
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Unit Tests
        run: ./gradlew --info --warning-mode=all clean test
