name: grantshares-ci-cd

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '8'
          cache: 'gradle'
      - name: Compile with neow3j
        run: ./gradlew clean neow3jCompile
      - name: Unit Tests
        run: ./gradlew --info --warning-mode=all clean test